"""Unique constraint on email


Revision ID: 835ef6eaf8e3
Revises: 794518869e5d
Create Date: 2021-03-05 17:38:01.194804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835ef6eaf8e3'
down_revision = '794518869e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_account_branch_uc', 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_account_branch_uc', 'member', type_='unique')
    # ### end Alembic commands ###
