"""Create Target model

Revision ID: ddf070b380d8
Revises: 8b2d856315a5
Create Date: 2021-03-05 21:21:38.454449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddf070b380d8'
down_revision = '8b2d856315a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('last_message_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('target_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'message', 'target', ['target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'target_id')
    op.drop_table('target')
    # ### end Alembic commands ###
